%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Ultimas modificacoes, 06/02/2012 - Alexandre Duarte 
%% Baseado no modelo latex de Isaac Maia (COPIN/UFCG)
%%
%% Para utilizar ese modelo sao necessarios os seguintes arquivos:
%%
%% ppgi.cls
%% ppgi.sty
%% mestre.sty
%%
%%
%% Mais detalhes sobre normas ABNT no latex, consultar http://abntex.codigolivre.org.br
%% Wiki interessante com dicas uteis sobre latex : http://www.tex-br.org
%%
%%
%% Para compilar esse arquivo, e' sempre importante fazer duas passagens com latex
%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\documentclass[a4paper,titlepage]{ppgi}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage[portuguese,ruled,linesnumbered]{algorithm2e}
\usepackage[english,portuges]{babel}
\usepackage{ppgi,mestre,epsfig}
\usepackage{times}
\usepackage[final]{pdfpages}
\usepackage{hyperref}
\hypersetup{
    bookmarks=true,   
    pdftitle={Monitor legislativo},
    pdfauthor={Vitor Márcio Paiva de Sousa Baptista}, 
    pdfsubject={Modelo de Documento Científico},
    pdfkeywords={Dissertação, Mestrado, PPGI, UFPB, modelo}, 
    colorlinks=true,
    linkcolor=black,
    citecolor=black,
    filecolor=black,
    urlcolor=black
 }

% Corrige bug no algorithm2e que usa termos em espanhol ao invés de português
\SetKwFor{Para}{para}{fa\c{c}a}{fim para}
\SetKwFor{ParaPar}{para}{fa\c{c}a em paralelo}{fim para}
\SetKwFor{ParaCada}{para cada}{fa\c{c}a}{fim para cada}
\SetKwFor{ParaTodo}{para todo}{fa\c{c}a}{fim para todo}

%-------------------------- Para usar acentuacaoo em sistemas ISO8859-1 ------------------------------------
% Se estiver usando o Microsoft Windows ou linux com essa codificacao, descomente essas linhas abaixo
% e comente as linhas referentes ao UTF8
%\usepackage[applemac]{inputenc} % Usar acentuacao em sistemas ISO8859-1, comentar a linha com  \usepackage[utf8x {inputenc}
%-----------------------------------------------------------------------------------------------------

%-------------------------- Para usar acentuacao em sistemas UTF8 ------------------------------------
% Para a maior parte das distribuicoes linux, usar essa opcao
\usepackage{ucs}
\usepackage[utf8x]{inputenc}
\usepackage[T1]{fontenc}
%-----------------------------------------------------------------------------------------------------
\usepackage{float}      
\usepackage{fancyvrb}
\usepackage{fancyheadings}
\usepackage{graphicx}
\graphicspath{{figure/}}
\setkeys{Gin}{width=0.5\textwidth}
\usepackage{longtable} %tabelas longas, para tabelas que ultrapassam uma pagina
\usepackage{minted} % Syntax highlighting para código
\usepackage{pdflscape} % landscape figures
\usepackage{glossaries} % Gerar glossário

\makeglossaries
\newacronym{IR}{IR}{Índice de Rice}
\newacronym{PT}{PT}{Partido dos Trabalhadores}
\newacronym{PSOL}{PSOL}{Partido Socialismo e Liberdade}
\newacronym{API}{API}{\emph{Application Programming Interface}}
\newacronym{XML}{XML}{\emph{eXtensible Markup Language}}
\newacronym{CSV}{CSV}{\emph{Comma Separated Values}}
\newacronym{JSON}{JSON}{\emph{JavaScript Object Notation}}
\newacronym{CEBRAP}{CEBRAP}{Centro Brasileiro de An\'alise e Pesquisa}

%\input{psfig.sty}
% ----------------- Para inserir codigo fonte de linguagens de programacao no documento -------------
\usepackage{listings}
\lstset{numbers=left,
stepnumber=1,
firstnumber=1,
numberstyle=\scriptsize,
extendedchars=true,
breaklines=true,
frame=tb,
basicstyle=\scriptsize,
stringstyle=\ttfamily,
showstringspaces=false
}
\renewcommand{\lstlistingname}{C\'odigo Fonte}
\renewcommand{\lstlistlistingname}{Lista de C\'odigos Fonte}

% ---------------------------------------------------------------------------------------------------

\selectlanguage{portuges}
\sloppy

\setcounter{secnumdepth}{4}
\setcounter{tocdepth}{4}
\usepackage{abnt-alf}

% Centraliza todos os floats
\makeatletter
\g@addto@macro\@floatboxreset\centering
\makeatother
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\Titulo{Monitor legislativo}
\Autor{Vitor Márcio Paiva de Sousa Baptista}
\Data{06 de Março de 2012}
\Area{Ciência da Computação}
\Pesquisa{Computação Distribuída | Sinais, Sistemas Digitais e Gráficos}
\Orientadores{Alexandre Nóbrega Duarte\\ (Orientador)}

\newpage
\cleardoublepage
\PaginadeRosto

\newpage
\cleardoublepage

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{resumo} 
\input{resumo.tex}
\end{resumo}
%\newpage
%\cleardoublepage

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{summary}
\input{abstract.tex}
\end{summary}

%\newpage
%\cleardoublepage

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% TMP: Agradecimentos
\begin{agradecimentos}
\input{agradecimentos.tex}
\end{agradecimentos}

\clearpage

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Definicao do cabecalho: secao do lado esquerdo e numero da pagina do lado direito
\pagestyle{fancy}
\addtolength{\headwidth}{\marginparsep}\addtolength{\headwidth}{\marginparwidth}\headwidth = \textwidth
\renewcommand{\chaptermark}[1]{\markboth{#1}{}}
\renewcommand{\sectionmark}[1]{\markright{\thesection\ #1}}\lhead[\fancyplain{}{\bfseries\thepage}]%
	     {\fancyplain{}{\emph{\rightmark}}}\rhead[\fancyplain{}{\bfseries\leftmark}]%
             {\fancyplain{}{\bfseries\thepage}}\cfoot{}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\Sumario
\ListadeSiglas
\listoffigures
\listoftables
\lstlistoflistings %lista de codigos fonte - Para inserir a listagem de
% codigos fonte

\newpage
\cleardoublepage
\Introducao


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Hifenizacao - Colocar lista de palavras que nao devem ser separadas e que 
% nao estao no dicionario portuges.
% As palavras do dicionario portuges ja sao separadas corretamente pelo lateX
%
\hyphenation{ gLite OurGrid GridDoctor }

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% A partir daqui coloque seus capitulos. Sugere-se que eles sejam inseridos com o comando \input
%% Da seguinte maneira:
%% 



\input{01-introducao}

\chapter{Fundamentação Teórica}\label{cap:fundamentacao}

\section{Ciência de Dados}

Segundo \citeonline{Stanton2012}, o termo Ciência de Dados (do inglês
\emph{Data Science}) é usado para definir uma área emergente que se ocupa da
coleta, preparo, análise, visualização, gestão e preservação de conjuntos de
dados com o objetivo de extrair conhecimento. Ela usa a ciência da computação
como ferramenta para extrair modelos estatísticos a partir de dados relativos a
uma área fim, como a ciência política.

Por ser uma área interdisciplinar e relativamente recente (especialmente no
Brasil) a distinção do que é ciência de dados e não estatística, matemática ou
computação pode ainda não ser muito clara \cite{Porto2014}. Para facilitar essa
diferenciação, \citeonline{Conway2013} criou o diagrama de Venn da figura
\ref{fig:ciencia-de-dados-venn} que mostra onde está a ciência de dados em
relação as outras áreas.

\begin{figure}[h]
\includegraphics{ciencia-de-dados-diagrama-venn}
\label{fig:ciencia-de-dados-venn}
\caption{Diagrama de Venn mostrando as habilidades necessárias para um
cientista de dados}
\end{figure}

Com as técnicas da ciência de dados, podemos responder perguntas como ``Qual a
melhor rota para chegar até meu trabalho?'', ``Vai chover hoje?'', ``Quais são
minhas chances de desenvolver câncer nos próximos 10 anos?''. Neste trabalho,
estamos interessados nas técnicas de desenvolvimento de modelos preditivos que,
baseados nos dados e conhecimento que temos do assunto, determinam a
probabilidade de acontecimentos futuros.

\subsection{Modelos preditivos}

\citeonline{Geisser1993} define modelagem preditiva como sendo ``o processo
pelo qual um modelo é criado ou escolhido para tentar melhor prever a
probabilidade de um resultado''. Já \citeonline{Kuhn2013} definem como ``o
processo de desenvolvimento de uma ferramenta ou modelo matemático que gere uma
previsão precisa''.

Independente da definição, modelos preditivos fazem parte do dia-a-dia da
sociedade atual. O Google os utiliza para interpretar o que seus usuários estão
buscando; o Netflix usa para recomendar filmes; corretoras de valores usam para
definir que ações comprar ou vender; seguradoras usam para definir qual o risco
e, consequentemente, o preço do seguro de um carro, entre outros
\cite{Levy2010}.

Existem duas principais categorias de problemas que podem ser resolvidos por
modelos preditivos: regressão e classificação. A diferença entre eles está no
tipo de resposta que queremos prever, se é contínua ou categórica, que
influencia nos tipos de modelos que podem ser usados e na forma de avaliá-los.
Por exemplo, ao analisarmos modelos que preveem o preço de um imóvel a partir
da sua área, buscamos o que chegue mais próximo do valor real\footnote{Esta é
uma simplificação. Existem diversas outras características a serem analisados
ao escolher um modelo, como facilidade de interpretação, velocidade de
execução, entre outras. Aqui consideramos que a única diferença entre eles seja
o resultado previsto.}. Já ao avaliar modelos que classifiquem imagens dos
dígitos 0 a 9, só nos interessamos na classificação correta; dois modelos que
identifiquem a imagem do número 1 como sendo do número 3 e 8 estão igualmente
errados. O que classificou como 3 não está ``menos errado'' do que o que
classificou como 8 \cite{Kuhn2013,Zumel2014}. Neste trabalho, nosso foco é em
classificação.

\subsubsection{Modelos de classificação}

% TODO: Concluir

% % Treinamento de algoritmos
% % Regressão VS Classificação

% Random Forest
% % Árvores de decisão

% Validação cruzada

\section{Modelos espaciais de votação}



A ideia básica de modelos espaciais de votação é que o conjunto de alternativas
políticas de uma votação pode ser tratado como uma dimensão em um espaço
euclidiano, e cada parlamentar tem preferências de valores nessa dimensão. O
voto seria então definido pela escolha da alternativa mais próxima da sua
preferência.

Há diversos modelos para estimar esses valores, como o NOMINATE, W-NOMINATE,
DW-NOMINATE, que são paramétricos; o Optimal Classification, que é
não-paramétrico, e; modelos baseados em estatística Bayesiana, como o IDEAL.
Nosso foco neste trabalho é no W-NOMINATE.
\cite{Poole2000,Poole2005,Poole2014,Jackman2000,Clinton2004}

Considere um exemplo onde 5 parlamentares votam em
dois projetos de Lei: um propondo a redução da maioridade penal de
18 para 16 anos e outra
propondo o aumento do salário-mínimo de R\$ 1.000 para
R\$ 1.200. Suponha que cada um tem uma única preferência
(\emph{single-peakedness}), conhecido como seu ponto ideal, e vota sinceramente
de acordo com ela. Considere também que as preferências são simétricas. Isto é,
dado duas escolhas a uma mesma distância do ponto ideal de um parlamentar, ele
será indiferente a qualquer uma delas.

Graficamente, temos a figura \ref{fig:modelo-espacial-votacao}, onde os pontos
representam as preferências dos legisladores sobre cada votação, representados
como as dimensões nesse espaço euclidiano. As linhas são chamadas linhas de
corte. Elas passam pelo ponto médio entre as duas alternativas em votação: a de
votar sim e a de votar não. Em outras palavras, se as escolhas são entre uma
maioridade penal de 16 ou
18, a linha de corte passa em $\frac{16 + 18}{2}$,
ou seja, $17$. Ela divide os legisladores que irão votar não, que estão a
esquerda da linha, dos que irão votar sim, que estão a direita da mesma. Caso
esteja em cima da linha de corte, ele é indiferente as alternativas.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{figure/tmp/modelo-espacial-votacao-1} \caption[Preferências de 5 deputados em 2 votações com suas respectivas linhas de corte]{Preferências de 5 deputados em 2 votações com suas respectivas linhas de corte}\label{fig:modelo-espacial-votacao}
\end{figure}


\end{knitrout}

Nesse exemplo estamos mostrando duas dimensões, mas o algoritmo é capaz de
estimar os pontos ideais em qualquer número de dimensões.

O comportamento dos parlamentares é assumido como sendo formado por dois
componentes: um determinístico e outro estocástico. Formalmente, definimos a
utilidade do legislador $i$ na consequência política do resultado ``sim'' da
votação $j$ como sendo:

\begin{equation}
  U_{ijy} = u_{ijy} + \epsilon_{ijy}
\end{equation}

onde $u_{ijy}$ é a parte determinística e $\epsilon_{ijy}$ é a parte
estocástica da função utilidade. Se não houver erro, o legislador vota sim se
$U_{ijy} > U_{ijn}$ e não se $U_{ijy} < U_{ijn}$. Caso $U_{ijy} = U_{ijn}$, ele
é indiferente para qualquer resultado.

\begin{description}
\item[$s$] o número de dimensões indexado por $k = 1, ..., s$;
\item[$p$] o número de parlamentares indexado por $i = 1, ..., p$;
\item[$q$] o número de votações indexado por $j = 1, ..., q$;
\item[$X_i$] o ponto ideal do parlamentar $i$ em um vetor de comprimento $s$;
\item[$Z_{jy}$ e $Z_{jn}$] a representação de cada votação em um vetor de comprimento
$s$, onde $y$ e $n$ são as consequências políticas dos resultados ``Sim'' e
``Não'', respectivamente.
\end{description}

A utilidade do parlamentar $i$ para a consequência $y$ em uma votação $j$ é:

\begin{equation}
  U_{ijy} = \beta \exp^{\left( - \frac{1}{2} \sum\limits_{k=1}^s w_k^2 d_{ijky}^2 \right)}
\end{equation}

Formalmente, sendo $O_{jy}$ e $O_{jn}$ os resultados correspondendo
respectivamente a um voto ``sim'' e um voto ``não'' na votação $j$ ($j = 1,
..., q$), definimos $Z_j$ como: 

\begin{equation}\label{eq:cutpoint}
  Z_j = \frac{O_{jy} + O_{jn}}{2}
\end{equation}

O $Z_j$ pode definir um ponto, linha, plano ou hiperplano, dependendo do número
de dimensões que estamos tratando. Ele é conhecido como ponto (ou linha, etc.)
de corte.

% Introdução

%% O que são de modelos de votação?

%% Por que os modelos espaciais de votação foram criados?

%% Por que não usar os votos diretamente?

% Desenvolvimento

% Conclusão

\subsection{Comparando pontos ideais ao longo do tempo}
\label{cap:fundamentacao:comparando-pontos-ideais-no-tempo}

O principal problema em comparar mudanças nos pontos ideais ao longo do tempo é
distinguir alterações causadas por mudanças na agenda legislativa das causadas
por mudanças no posicionamento dos parlamentares \cite{Bailey2007}. Em outras
palavras, se o ponto ideal de um deputado federal passa de 0.3 para -0.2 de um ano
para o outro, como descobrir se isso representa uma mudança real de ideologia ou
é somente reflexo da diferença na agenda legislativa dos dois períodos?

Segundo \citeonline{Shor2010}, todos os esforços para resolver esse problema
usam ``pontes'', que podem ser parlamentares cujo posicionamento assume-se ter
se mantido estável durante o período de interesse, ou; projetos de Lei que
foram votados em mais de um momento (nas duas casas legislativas em um sistema
bicameral, por exemplo). O primeiro é mais usado para comparar as mudanças nos
posicionamentos dos parlamentares, enquanto o segundo permite unir pessoas que
não votaram juntas em um mesmo mapa espacial\footnote{Por exemplo,
\citeonline{Shor2010} colocam todos os legisladores de 11 estados americanos e
do congresso federal em um período que varia entre 7 e 15 anos, dependendo do
estado, em um mesmo mapa espacial}. \citeonline{Poole2005} propõe duas formas
para estimar pontos ideais usando pontes.

Na primeira, batizada de \emph{pooled scaling} por \citeonline{Shor2010},
dividimos os votos dos parlamentares que queremos mensurar em dois
parlamentares ``virtuais'', um com os votos antes e outro com os votos depois
da data de interesse. Unimos esses parlamentares virtuais com os
parlamentares-ponte, que possuem um registro único, em uma tabela individual e
executamos o algoritmo de estimação dos pontos ideais. Ao final, teremos dois
pontos para cada parlamentar de interesse e um ponto para os pontes. Na
segunda, que \citeonline{Shor2010} chamam de \emph{linear mapping}, estimamos
os pontos ideias separadamente em cada período e os conectamos usando regressão
entre os conjuntos de pontos dos parlamentares-ponte. Ambas formas devem gerar
resultados similares, mas a segunda é computacionalmente mais simples, o que
pode ser essencial, dependendo da quantidade de parlamentares e votações votos
em estudo.

\citeonline{Poole2005} ainda descreve uma terceira forma, similar a
\emph{pooled scaling} descrita acima, que usa para testar se os senadores
norte-americanos mudam de comportamento nos últimos dois anos de seus mandatos,
antes de concorrer à reeleição. Neste caso, ele quer calcular a mudança de
comportamento de todos os legisladores em dois momentos numa mesma legislatura.
Se usássemos o \emph{pooled scaling} diretamente, precisaríamos escolher alguns
parlamentares como pontes que, por definição, não teriam mudado de
comportamento. Ao invés disso, ele segue o seguinte processo:

\begin{enumerate}
  \item Para cada parlamentar, faça:
    \begin{enumerate}
      \item Transforme-o em dois parlamentares ``virtuais'', um com o conjunto
de votos antes, e outro com os depois da data de interesse. Os outros
parlamentares não são modificados;
      \item Calcule os pontos ideias;
      \item Guarde os resultados dos dois parlamentares ``virtuais''. A
diferença entre suas posições representa a mudança de comportamento do
parlamentar.
    \end{enumerate}
  \item Calcule medidas de incerteza para as estimativas.
\end{enumerate}

Ao final, ele tem dois pontos para cada senador: um representando sua posição
nos primeiros 4, e o outro nos últimos 2 anos da legislatura. Note que, como as
matrizes de votações usadas para gerar os mapas espaciais são diferentes, eles
não são estritamente comparáveis. Apesar disso, \citeonline{Poole2005}
argumenta que como elas possuem o mesmo conjunto de votos, com a única
diferença de que um dos parlamentares foi dividido em dois, ele considera ser
seguro compará-las.

\section{Processo legislativo}

Como são criadas as Leis no Brasil? Essa seção pode ser gigantesca, então acho melhor focar no essencial e pontuar as características mais importantes para este trabalho, por exemplo o que são destaques, tipos de votação, tipos de votos, etc.

% ALEXANDRE: Acho que senado e câmara podem ser subseções desta seção.
% Essas subseções não precisam ser muito longas. Devem descrevas basicamente as competências e atribuições de cada casa.
%
% Acho que a justificativa da escolha da Câmara pode aparecer mais tarde, na seção do estudo de caso.  
% Assim a seção de fundamentação teórica fica sendo realmente apenas de fundamentação teórica, sem efeitos colaterais.

\subsection{Senado Federal}

Também chamada de Casa Alta, ela é composta por 81 senadores, 3 por cada Estado e Distrito Federal. Os senadores têm mandato de 8 anos e são eleitos pelo sistema majoritário\footnote{No sistema majoritário, o candidato mais votado é eleito. Nos anos em que são eleitos 2 senadores, os dois candidatos mais votados serão eleitos. Ele pressupõe um (ou dois) único candidatos por partido. É o mesmo sistema usado nas eleições para os chefes do Poder Executivo (presidente da República, governadores e prefeitos). Com exceção da eleição de senadores e prefeitos em cidades com menos de 200 mil habitantes, onde há um único turno, as eleições ocorrem em dois turnos. \cite{Netto2013}}. A renovação da casa é parcial, modificando $\frac{1}{3}$ e $\frac{2}{3}$ dos senadores alternadamente de 4 em 4 anos.

\subsection{Câmara dos Deputados}

Também chamada de Casa Baixa ou Casa do Povo, ela é composta por 513 deputados federais, cujo papel é representar o povo. Cada Estado ou Distrito Federal elege entre 8 e 70 deputados, proporcionalmente a sua população. Os deputados têm mandato de 4 anos, eleitos pelo sistema proporcional\footnote{No sistema proporcional os partidos registram vários candidatos para o mesmo cargo. Os votos recebidos por cada candidato são direcionados ao partido, que precisa atingir uma quantidade mínima de votos (chamado quociente eleitoral) para eleger ao menos um de seus candidatos. Nesse sistema, um candidato com menos votos pode se eleger, enquanto outro com mais votos não se elegeu, dependendo do partido de cada um deles. \cite{Netto2013,Bramatti2014}}. Diferente do Senado Federal, a renovação é total de 4 em 4 anos.

\section{Ciência de dados}

Texto bem geral sobre data science. Pode ser interessante falar sobre algum algoritmo específico que eu vá usar, ou talvez seja melhor explicá-los no miolo da dissertação.

\section{Considerações Finais}
\input{03-trabalhos-relacionados}



\chapter{Miolo da sua dissertação}\label{cap:miolo}

Nessa parte pretendo falar sobre a ferramenta desenvolvida, mostrar sua arquitetura e como cada parte funciona e pode ser modificada.

\section{Os dados}

% TODO: Explicar as características dos dados

Para desenvolver o modelo preditivo, precisamos de dois conjuntos de dados: os
resultados das votações nominais na Câmara dos Deputados e informações sobre as
coalizões governamentais. Nessa seção descreverei o processo de extração,
limpeza, transformação e carga\footnote{Do inglês, \emph{extract, clean,
transform and load} (ECTL)} desses dados, desde suas fontes até estarem prontos
para uso no modelo. Nosso objetivo é criar uma tabela como a
\ref{table:dataset-final}, com os valores dos pontos ideais dos deputados
federais (nossas variáveis independentes) e uma coluna definindo se eles
mudaram de posicionamento ou não no período (nossa variável dependente).

Nos restringimos a analisar da 50\textordfeminine{} até a 54\textordfeminine{}
legislatura, que compreende o período de 20 anos entre o início do primeiro
governo de Fernando Henrique Cardoso (FHC) em 1995 até o final do primeiro
governo de Dilma Rousseff em 2015. Escolhemos começar a análise no governo de
FHC pois é quando, de acordo com \citeonline{Freitas2008}, termina a fase de
acomodação dos parlamentares as regras definidas pela Constituição de 1988.

\begin{table}
\centering
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\begin{tabular}{r|r|l}
\hline
antes & depois & mudou\_coalizao\\
\hline
0.55 & -0.40 & Sim\\
\hline
0.90 & 0.85 & Não\\
\hline
-0.30 & 0.40 & Sim\\
\hline
\end{tabular}


\end{knitrout}
\caption{Exemplo da tabela usada para treinar o algoritmo.}
\label{table:dataset-final}
\end{table}

\subsection{Extração}
\label{sec:miolo:extracao}

O \gls{CEBRAP} reúne diversos dados sobre o legislativo brasileiro. Para este
trabalho, extraímos dele a lista das coalizões governamentais do Brasil.
\citeonline{Figueiredo2007} se inspirou no trabalho de \citeonline{Muller2000}
para definir os critérios de início de uma nova coalizão. Eles são: i) a
mudança da legislatura, e; ii) alterações no conjunto de partidos que controlam
os ministérios. Com base nisso, \citeauthor{Figueiredo2007} listou as coalizões
formadas durante as duas últimas constituições democráticas, nos períodos de
1946 até 1964, e de 1988 até os dias atuais.  

De posse desses dados, também precisamos do resultado das votações nominais
ocorridas na Câmara Federal. O banco de dados do \gls{CEBRAP} possui essas
informações, mas como o modelo desenvolvido foi pensado para ser usado
continuamente, monitorando o comportamento dos deputados federais, preferimos
buscá-los diretamente da fonte.

A Câmara disponibiliza diversos conjuntos de dados em seu sua página na
web\footnote{\url{http://www2.camara.leg.br/transparencia/dados-abertos}}.
Dentre eles está o histórico dos resultados das votações nominais que
precisamos. Infelizmente, até a data de escrita deste trabalho, esses dados só
estavam disponíveis para consulta individualmente através de uma \gls{API}, mas
precisávamos do conjunto completo para análise local.  Isto nos obrigou a
desenvolver um software que busca, uma a uma, as votações ocorridas no nosso
período de interesse.

Esse software\footnote{Disponível em:
\url{https://github.com/vitorbaptista/dados-abertos-camara.gov.br}}, conhecido
como \emph{crawler} (do inglês, ``raspador''), usa os métodos
\emph{ListarProposicoesVotadasEmPlenario}, que a partir de um ano retorna a
lista de proposições votadas, e \emph{ObterVotacaoProposicao}, que retorna
todas as votações ocorridas em uma proposição a partir do seu tipo, número e
ano. Ele foi desenvolvido em Python usando a biblioteca Scrapy
\cite{Python276,Scrapy}. Além de baixar os dados, ele também converte a lista
de proposições votadas em um \gls{CSV} e as votações por proposição em um
\gls{JSON}, a partir do original em \gls{XML}, pois mais ferramentas suportam
esses formatos.

\subsection{Limpeza}

Usando outro programa também desenvolvido em Python\footnote{Disponível em:
\url{https://github.com/vitorbaptista/codigo-mestrado}}, limpamos os dados
extraídos fazendo:

\begin{itemize}
  \item Retiramos espaços em branco no começo ou final dos campos;
  \item Normalizamos os nomes dos partidos seguindo o padrão adotado pelo
\gls{CEBRAP}, onde mudanças de nome são identificados pela primeira e última
sigla (ex.: PJ se torna PRN que se torna PJC, então temos PJ>PTC) e fusões são
identificados pelo maior partido na data da fusão e o novo nome (ex.: PL e
PRONA se tornam PL>PR) \cite{Freitas2008}. A lista completa está no apêndice
\ref{apendice:lista-partidos}.
\end{itemize}

O resultado dessa etapa é guardado em um banco de dados SQLite com o auxílio da
biblioteca SQLAlchemy \cite{SQLite3,SQLAlchemy}. A partir daí, geramos dois
arquivos \gls{CSV} por legislatura: um contendo os dados dos parlamentares e
seus votos (tabela \ref{table:votes}) e outro contendo os detalhes das votações
(tabela \ref{table:votes-metadata}). São esses arquivos 

\begin{table}
\centering
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\begin{tabular}{r|l|l|l|r|r|r|r|r}
\hline
id & name & party & state & 76 & 273 & 271 & 272 & 485\\
\hline
3151 & Jairo Ataíde & PFL>DEM & MG & NA & 0 & NA & 0 & NA\\
\hline
4929 & Joseph Bandeira & PT & BA & NA & NA & NA & NA & NA\\
\hline
4930 & Silvio Costa & PSC & PE & 1 & 0 & 0 & 0 & 0\\
\hline
4931 & Izalci & PL+PRONA>PR & DF & 1 & 1 & 0 & 0 & 0\\
\hline
62881 & Danilo Forte & PMDB & CE & 1 & 1 & 0 & 0 & NA\\
\hline
67138 & Iracema Portella & PDS>PP & PI & 1 & 1 & 0 & 0 & 0\\
\hline
\end{tabular}


\end{knitrout}
\caption{Exemplo da tabela com detalhes dos parlamentares e seus respectivos votos.}
\label{table:votes}
\end{table}

\begin{landscape}
\begin{table}
\centering
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\begin{tabular}{r|r|r|l|l|l}
\hline
id & id\_sessao & proposicao\_id & data & resumo & obj\_votacao\\
\hline
76 & 4212 & 491974 & 2011-02-15 21:09:00 & Aprovado o Requerime... & URGÊNCIA PARA O PL 3...\\
\hline
273 & 4215 & 491872 & 2011-02-16 00:17:00 & Mantida a expressão.... & DVS - Bloco PvPps - ...\\
\hline
271 & 4214 & 491872 & 2011-02-16 22:38:00 & Rejeitada a Emenda d... & DVS - PSDB - EMENDA ...\\
\hline
272 & 4214 & 491872 & 2011-02-16 23:27:00 & Rejeitada a Emenda d... & DVS - DEM - EMENDA N...\\
\hline
485 & 4219 & 485274 & 2011-02-22 17:36:00 & Rejeitado o Requerim... & REQUERIMENTO DE RETI...\\
\hline
486 & 4219 & 485274 & 2011-02-22 19:20:00 & Rejeitado o Requerim... & REQUERIMENTO DE ADIA...\\
\hline
487 & 4220 & 485274 & 2011-02-22 20:45:00 & Rejeitado o Requerim... & REQUERIMENTO DE RETI...\\
\hline
955 & 4221 & 485275 & 2011-02-23 17:01:00 & Rejeitado o Requerim... & REQUERIMENTO DE RETI...\\
\hline
1042 & 4251 & 485758 & 2011-04-05 17:02:00 & Rejeitado o Requerim... & REQUERIMENTO DE RETI...\\
\hline
1043 & 4251 & 485758 & 2011-04-05 19:11:00 & Rejeitado o Requerim... & REQUERIMENTO DE CONC...\\
\hline
\end{tabular}


\end{knitrout}
\caption{Exemplo da tabela com detalhes das votações. Os campos ``resumo'' e
``obj\_votacao'' foram limitados a 20 caracteres por
questões de formatação da página.}
\label{table:votes-metadata}
\end{table}
\end{landscape}

\subsection{Transformação}
\label{sec:miolo:transformacao}

Nesta etapa, calculamos a mudança na posição dos pontos ideais dos deputados
federais entre os dois períodos de interesse e definimos se, segundo os dados
do \gls{CEBRAP}, houve ou não uma alteração na coalizão no período.

O cálculo da mudança nos pontos ideais é feito segundo a metologia de
\citeonline{Poole2005} descrita na sessão
\ref{cap:fundamentacao:comparando-pontos-ideais-no-tempo}. Para isso,
desenvolvemos um programa\footnote{Disponível em:
\url{https://github.com/vitorbaptista/codigo-mestrado}} na linguagem R usando e
as bibliotecas wnominate e pscl \cite{R,R:wnominate,R:pscl}.

Existem duas variáveis que precisam ser definidas para usarmos a metodologia de
\citeauthor{Poole2005}: os períodos de análise da mudança de comportamento e o
número de repetições para cálculo do erro das estimativas. Com relação ao
cálculo do erro, \citeauthor{Poole2005} recomenda 101 repetições. Apesar disso,
nos limitamos a 10 repetições por restrições na nossa capacidade de
processamento.

Para definir os períodos de análise, levamos em consideração os critérios de
escolha de votações do W-NOMINATE, que exige ao menos 20 votações com no mínimo
2,5\% de votos contrários a maioria. Definimos períodos de 12 meses dentro de
uma mesma legislatura, divididos em duas partes de mesmo tamanho (o primeiro e
o último semestre). Esses períodos iniciam no primeiro dia de cada mês, desde o
01/Fev do primeiro ano da legislatura até o do penúltimo. Por exemplo, na
54\textordfeminine{} legislatura, o primeiro período foi de 01/Fev/2011 até
01/Fev/2012 (dividido em 01/Ago/2011), e o último foi de 01/Fev/2014 até
01/Fev/2015. Existem 37 desses períodos por legislatura.

\begin{table}
\centering
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\begin{tabular}{r|r|r|r}
\hline
Legislatura & Deputados Federais & Votações & Votos\\
\hline
50 & 631 & 468 & 178603\\
\hline
51 & 624 & 419 & 155737\\
\hline
52 & 614 & 451 & 134461\\
\hline
53 & 606 & 619 & 192879\\
\hline
54 & 644 & 432 & 131552\\
\hline
\end{tabular}


\end{knitrout}
\caption{Número de deputados federais e votações por legislatura}
\label{table:estatisticas-legislaturas}
\end{table}

Na tabela \ref{table:estatisticas-legislaturas}, mostramos o número de
deputados federais e votações por legislatura. Consideramos deputados federais
todos parlamentares que participaram de alguma votação na Câmara dos Deputados
no período, por isso o número é maior do que o número de cadeiras. Por
legislatura, temos em média 623,80 deputados e
477,80 votações com 332,04 votos cada.

\section{Construção do modelo}

% TODO: Preciso falar sobre a variável de coalizão, de onde ela veio, como é
% definida e como a usamos. Também preciso falar do período de estudo (100
% votações).

\subsection{Variável dependente}

A variável dependente indica se o parlamentar entrou ou saiu da coalizão do
governo no período de estudo. Ela pode tomar os valores \verb|N|, caso ele
tenha se mantido no governo ou oposição, ou \verb|S| caso tenha trocado de
lado. Um favor importante é como definimos o período de estudo, ou seja, quando
consideramos que um parlamentar mudou de lado?

Se considerarmos que ele mudou de lado somente quando seu partido entrou (ou
saiu) da coalizão, o objetivo deste trabalho, de prever quando um parlamentar
vai mudar de posicionamento com base no padrão de votação, é impossível. Se um
parlamentar só muda de comportamento depois de entrar (ou sair) oficialmente da
coalizão, na melhor hipótese nosso algoritmo conseguiria detectar as datas de
entrada (ou saída). Em outras palavras, não conseguiríamos prever essa mudança.
Por isso, a hipótese essencial para nosso trabalho é que os parlamentares mudam
de comportamento antes de entrarem (ou saírem) da coalizão. Mas quanto antes?

Se escolhermos um período maior do que o real, estaremos ``ensinando'' nosso
algoritmo algo errado. Se, por outro lado, escolhermos um período menor, também
teremos problemas. Como complicador, é provável que não exista um valor correto
em todas as ocasiões. Algumas vezes, a mudança de comportamento pode acontecer
2 meses antes da mudança oficial de posicionamento; outras, ela pode ocorrer 10
meses antes. Como escolher, então?

Não há uma resposta fácil para esta pergunta. Neste trabalho, considerei os 6
meses antes da mudança oficial de posicionamento. Obtive bons resultados, mas
este é um ponto que pode ser melhor estudado, tanto usando outros valores,
quanto analisando se esses valores mudam dependendo da legislatura.

\subsection{Variáveis independentes}

Usamos os pontos ideais do parlamentar estimado usando o W-NOMINATE e seus
respectivos erros-padrão como variáveis independentes.

\section{Considerações Finais}

Desenvolvi uma ferramenta que extrai dados de diversas fontes, os consolida, analisa e gera relatórios para os usuários. Cada parte pode ser modificada e expandida, e os dados (e algoritmos) podem ser usados por outras pessoas. Daqui falta validar que os algoritmos na parte de análise geram algo interessante.
\input{05-avaliacao-experimental}
\input{06-conclusao}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% BIbliografia
%% Coloque suas referencias no arquivo ref.bib

\bibliographystyle{abnt-alf} % estilo de bibliografia   plain,unsrt,alpha,abbrv.
\bibliography{ref} % arquivos com as entradas bib.

%Faz aparecer a referencia bibliografica no indice
\addcontentsline{toc}{section}{\numberline{}Referências Bibliográficas}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Apendice
% Caso seja necessario algum apendice

\appendix
\input{apendice-lista-dos-partidos}



\chapter{A saída do PSB da coalizão em Dilma I}\label{cap:analise-saida-psb}

\section{Introdução}

O PSB esteve na base de apoio do governo do PT desde que o partido conquistou a
Presidência da República com Lula em 2003. Dez anos depois, em 2013, penúltimo
ano do primeiro governo de Dilma, o PSB anuncia a candidatura de Eduardo Campos
para a presidência, rompendo a aliança com o PT.

Para entender a repercussão dessa mudança na Câmara dos Deputados, analisaremos
as votações nominais ocorridas naquela legislatura (54\textordfeminine, que
durou de 2011 até 2015) seguindo a metodologia proposta por Keith Poole em
\emph{Spatial models of parliamentary voting} \cite{Poole2005}.
% Não estamos entendendo a repercussão da mudança na CD como um todo, mas sim
% só no comportamento de votação dos parlamentares.

\section{Metodologia}{\label{sec:analise-saida-psb:metodologia}

Para entender a influência da saída do PSB no comportamento de votação dos
parlamentares, precisamos de uma forma de comparar o comportamento deles antes
e depois dessa mudança. Este é um problema complicado, estudado por diversos
autores (CITATION NEEDED). Nesta análise seguimos a metodologia de
\cite{Poole2005}.

Considerando um parlamentar por vez, o substituímos por dois parlamentares
``virtuais'' na tabela de votações, um com os votos antes da mudança e outro
com os votos depois dela, e executamos o algoritmo W-NOMINATE nessa nova
tabela. Esse procedimento é repetido para cada parlamentar separadamente,
enquanto mantém todos os outros sem modificações. Ao final, teremos dois pontos
para cada parlamentar: um para antes e outro para depois da mudança. A
diferença entre esses pontos representa o nível da mudança de comportamento no
período de análise. 

Por exemplo, considere a tabela \ref{table:exemplo-mudanca-de-comportamento}
contendo 3 parlamentares e 4 votações. Para definir qual foi a mudança de
comportamento de Samara entre as votações 2 e 3, dividimos seus votos em dois
parlamentares ``virtuais'', Samara 1 e Samara 2 (ver tabela
\ref{table:exemplo-parlamentar-virtual}), e executamos o algoritmo W-NOMINATE.
Guardamos os resultados de Samara e repetimos os mesmos passos para Pedro e
depois Maria. Ao final, teremos dois pontos para cada parlamentar: um relativo
a sua posição antes, e outro depois da mudança (ver figura
\ref{fig:exemplo-mudanca-de-comportamento}). A distância desses dois pontos é
uma medida da intensidade da mudança do parlamentar.  Comparando as distâncias
de cada parlamentar, podemos determinar se a mudança é significante ou não.

% TODO: Falar sobre o parametric bootstrap
% TODO: Falar sobre os problemas em comparar esses valores.
% \begin{quote}
%   ``(...) all matrices have the same number of nonmissing entries, and they
%   differ only in the fact that each has a different senator divided into two
%   records. Consequently, I believe it's safe to capture the 72 distances with
%   each other, because the differences between the configurations will be
%   trivial.''\cite{Poole2005}
% \end{quote}

\begin{table}
  \begin{minipage}{\textwidth}
    \centering
    \begin{tabular}{ l l l l l }
      nome & votação1 & votação2 & votação3 & votação4 \\
      \hline
      Samara & Sim & Sim & Não & Não \\
      Pedro & Sim & Sim & Sim & Sim \\
      Maria & Não & Não & Não & Não \\
    \end{tabular}
    \caption{Dados originais de votação}
    \label{table:exemplo-mudanca-de-comportamento}
  \end{minipage}
  \begin{minipage}{\textwidth}
    \centering
    \begin{tabular}{ l l l l l }
      nome & votação1 & votação2 & votação3 & votação4 \\
      \hline
      Samara 1 & Sim & Sim & & \\
      Samara 2 & & & Não & Não \\
      Pedro & Sim & Sim & Sim & Sim \\
      Maria & Não & Não & Não & Não \\
    \end{tabular}
    \caption{Dados de votação com Romário dividido no meio}
    \label{table:exemplo-parlamentar-virtual}
  \end{minipage}
\end{table}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{figure/tmp/exemplo-mudanca-de-comportamento-1} \caption[Posições dos parlamentares antes e depois da data em análise]{Posições dos parlamentares antes e depois da data em análise}\label{fig:exemplo-mudanca-de-comportamento}
\end{figure}


\end{knitrout}

% Pseudocódigo
%
% \begin{enumerate}
%   \item Para cada parlamentar, faça:
%   \begin{enumerate}
%     \item Crie dois parlamentares ``virtuais'', um com os votos do parlamentar
%       antes da mudança, e o outro com os votos depois dela;
%     \item Execute o W-NOMINATE na matriz completa de votações com todos os
%       parlamentares e o parlamentar em análise substituído pelos parlamentares
%       ``virtuais'';
%     \item Guarde o resultado;
%   \end{enumerate}
%   \item Compara a mudança de cada parlamentar de interesse com todos os outros,
%     para descobrir se ela (a mudança) foi significativa.
% \end{enumerate}

\section{Extração dos dados}



Os dados das votações nominais foram extraídos a partir da API disponibilizada
no site da Câmara dos Deputados. Eles compreendem 131.552 votos
proferidos por 644 parlamentares em 432
votações. A figura \ref{fig:votacoes-por-mes} mostra a distribuição das
votações no período e a figura \ref{fig:deputados-por-partido} mostra o número
de deputados federais por partido. Só consideramos votos \verb|Sim| ou
\verb|Não|.  

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{figure/tmp/votacoes-por-mes-1} \caption[Distribuição de votações por mês na 54\textordfeminine{} legislatura]{Distribuição de votações por mês na 54\textordfeminine{} legislatura}\label{fig:votacoes-por-mes}
\end{figure}


\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{figure/tmp/deputados-por-partido-1} \caption[Distribuição de Deputados Federais por partido na 54\textordfeminine{} legislatura]{Distribuição de Deputados Federais por partido na 54\textordfeminine{} legislatura}\label{fig:deputados-por-partido}
\end{figure}


\end{knitrout}

\section{Análise}



Seguindo a metodologia descrita na sessão
\ref{sec:analise-saida-psb:metodologia}, dividimos a
54\textordfeminine{} legislatura na votação mais próxima da data de interesse,
no nosso caso, a data em que o PSB deixa a coalizão do governo. De acordo com
os dados disponíveis no banco de dados do CEBRAP, isso ocorreu em 03/10/2013. A
primeira votação depois dessa data ocorreu em
08/10/2013 (identificador
367), relacionada ao MPV 621/2013. Houve
303 votações antes da ruptura e
133 votações após. Dos 643
parlamentares que votaram ao menos uma vez nesse período,
470 passaram pelo nosso filtro de
participação em ao menos 20 votações cuja minoria teve 2,5\% ou mais dos votos.

A figura \ref{fig:boxplot-diff-coalizao} mostra a distribuição da diferença
entre as posições dos parlamentares antes e depois da saída do PSB da base do
governo, agrupado pelos que entraram ou saíram da coalizão e os que mantiveram
sua posição. Nela podemos ver que, no geral, quem entra na coalizão se torna
mais governista, quem sai se torna mais oposicionista, e os outros mantém sua
posição, mas existem diversos \emph{outliers}.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{figure/tmp/boxplot-diff-coalizao-1} \caption[Distribuição do nível de mudança da posição dos deputados federais antes e depois da saída do PSB da coalizão do governo]{Distribuição do nível de mudança da posição dos deputados federais antes e depois da saída do PSB da coalizão do governo}\label{fig:boxplot-diff-coalizao}
\end{figure}


\end{knitrout}

Na tabela \ref{table:top-10-diffs} estão os dez parlamentares com maior mudança
de posição em valores absolutos. Desses, analisemos os que não entraram nem
saíram da coalizão: 

\begin{description}
\item[Dudimar Paxiuba] Apesar de continuar fora da coalizão, ele saiu do PSDB
para o PROS em 2013, o que explicaria essa aproximação ao
governo\footnote{\url{http://www2.camara.leg.br/deputados/pesquisa/layouts_deputados_biografia?pk=193033&tipo=0}}.
\item[Rebecca Garcia] Não consegui explicar. A única coisa que encontrei foi
que ela ia se candidatar a prefeitura de Manaus em 2012, mas desistiu porque
vazou um áudio de uma conversa dela com seu amante na época, o ex-vereador Ari
Moutinho. Não me parece ter relação.
\item[Vicente Candido]Também não encontrei uma razão.
\item[Dr. Grilo]Saiu do PSL para o Solidariedade, que pode explicar o
afastamento do governo.
\end{description}

\begin{table}
\centering
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\begin{tabular}{l|l|l|r|r|r}
\hline
Nome & Partido & Coalizão & Antes & Depois & Diferença\\
\hline
Wladimir Costa & PMDB & saiu & 0.32 & -0.60 & -0.92\\
\hline
Dudimar Paxiuba & PROS & nao\_mudou & -0.71 & 0.17 & 0.87\\
\hline
Luiz Nishimori & PL+PRONA>PR & entrou & -0.86 & -0.08 & 0.77\\
\hline
Domingos Dutra & PT & saiu & 0.52 & -0.16 & -0.68\\
\hline
Romário & PSB & saiu & 0.28 & -0.37 & -0.65\\
\hline
Genecias Noronha & PMDB & saiu & -0.01 & -0.64 & -0.63\\
\hline
Rebecca Garcia & PDS>PP & nao\_mudou & 0.39 & -0.23 & -0.62\\
\hline
Antonio Balhmann & PROS & saiu & 0.08 & 0.69 & 0.61\\
\hline
Vicente Candido & PT & nao\_mudou & 0.99 & 0.39 & -0.60\\
\hline
Dr. Grilo & PSL & nao\_mudou & 0.05 & -0.52 & -0.57\\
\hline
\end{tabular}


\end{knitrout}
\caption{Os dez parlamentares com maior diferença absoluta entre suas posições
antes e depois da saída do PSB da base do governo.}
\label{table:top-10-diffs}
\end{table}

\subsection{Os deputados do PSB mudaram de comportamento?}



De acordo com a figura \ref{fig:mudanca-psb}, no geral os deputados do PSB se
afastaram do governo, enquanto a maioria dos parlamentares dos outros partidos
mantiveram suas posições. Há um \emph{outlier} nos deputados do PSB que, ao
contrário da maioria, se aproximou do governo: Alexandre Toledo, que
passou de -0,61 para -0,10 (diferença
de 0,51). Analisando este caso, a razão se torna clara: ele
era do PSDB e passou para o PSB em 2013. Apesar do PSB ter se tornado oposição,
passando de uma posição mediana -0,01
para -0,33, o PSDB é um opositor mais
ferrenho ao governo, com posição mediana -0,87.

Com base nesses dados, podemos concluir que o que já esperávamos: o PSB se
afastou do governo.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{figure/tmp/mudanca-psb-1} \caption[Distribuição do nível de mudança da posição dos deputados federais antes e depois da saída do PSB da coalizão do governo]{Distribuição do nível de mudança da posição dos deputados federais antes e depois da saída do PSB da coalizão do governo}\label{fig:mudanca-psb}
\end{figure}


\end{knitrout}

\section{Modelagem}

Nosso objetivo agora é determinar se, baseado somente nas posições dos
deputados federais de antes e depois da saída do PSB da coalizão, conseguimos
inferir se um parlamentar mudou de lado (se era governo, se tornou oposição, ou
vice-versa). Para isso, treinaremos um modelo \emph{Random Forest}.

O primeiro passo é alterar a coluna ``Coalizão'' para somente dois valores: sim
ou não. Nesse momento, nosso objetivo é determinar se o parlamentar mudou de
lado, e não pra que lado ele foi\footnote{Sabendo se o parlamentar mudou de
lado e qual era sua posição anterior, podemos inferir qual é sua nova posição
(e.x.: se ele era oposição e mudou de lado, agora virou governo).}. Também
retiraremos informações como nome e partido e parlamentares cuja posição não
conseguimos estimar pois não houve votos o suficiente, e adicionamos o
desvio-padrão de cada valor\footnote{Calculados usando parametric bootstrap.
TODO: Explicar melhor}. No final, teremos uma tabela como a
\ref{table:clean-data}.

\begin{table}
\centering
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\begin{tabular}{r|r|r|r|r|l}
\hline
Antes & Antes SD & Depois & Depois SD & Diferença & Mudou de posição\\
\hline
0.32 & 0.17 & -0.60 & 0.16 & -0.92 & Sim\\
\hline
-0.71 & 0.12 & 0.17 & 0.08 & 0.87 & Não\\
\hline
-0.86 & 0.10 & -0.08 & 0.19 & 0.77 & Sim\\
\hline
0.52 & 0.13 & -0.16 & 0.13 & -0.68 & Sim\\
\hline
0.28 & 0.10 & -0.37 & 0.20 & -0.65 & Sim\\
\hline
-0.01 & 0.12 & -0.64 & 0.15 & -0.63 & Sim\\
\hline
\end{tabular}


\end{knitrout}
\caption{Os dez parlamentares com maior diferença absoluta entre suas posições
antes e depois da saída do PSB da base do governo.}
\label{table:clean-data}
\end{table}

Com os dados nesse formato, agora precisamos dividí-lo em dois grupos: um para
treino e um para teste. Precisamos fazer isso para que as estimativas de
precisão do nosso modelo sejam confiáveis. Escolhemos manter 80\% para treino e
20\% para testes. Também usamos o \emph{10-fold stratified cross validation}.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
## note: only 30 unique complexity parameters in default grid. Truncating the grid to 30 .
\end{verbatim}
\end{kframe}
\end{knitrout}

O modelo foi treinado com todos os atributos na tabela \ref{table:clean-data} e
a interação entre eles. Analisamos diversos números de preditores e, como pode
ser visto na figura \ref{fig:roc-vs-mtry}, o melhor modelo com relação ao área
sob a curva ROC usou 25 preditores e chegou a área de
0,86 com desvio-padrão de 0,06.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{figure/tmp/roc-vs-mtry-1} \caption[ROC como função do número de preditores]{ROC como função do número de preditores.}\label{fig:roc-vs-mtry}
\end{figure}


\end{knitrout}

Usando os dados de teste, podemos avaliar nosso modelo. A figura \ref{fig:roc}
mostra a curva ROC. Ela mostra a sensibilidade e especificidade do nosso modelo
para diversos pontos de corte. O valor marcado é o ponto ``ideal'', definido
como o ponto mais próximo do canto superior esquerdo do gráfico (sensibilidade
e especificidade iguais a 1). Na tabela \ref{table:roc} podemos ver todos
máximos locais dos pontos de corte e as respectivas sensibilidades e
especificidades, com mínimos e máximos dentro de margem de confiança de
95\%\footnote{Calculado a partir de 2.000 stratified bootstrap replications.
TODO: explicar melhor}.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{figure/tmp/roc-1} \caption[Curva ROC com ponto ``ideal'' marcado]{Curva ROC com ponto ``ideal'' marcado.}\label{fig:roc}
\end{figure}


\end{knitrout}

\begin{table}
\centering
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\begin{tabular}{l|r|r|r|r|r|r}
\hline
cutpoint & sens.low & sens.median & sens.high & spec.low & spec.median & spec.high\\
\hline
0.9 & 0.00 & 0.13 & 0.33 & 0.96 & 0.99 & 1.00\\
\hline
0.739 & 0.00 & 0.20 & 0.40 & 0.91 & 0.96 & 1.00\\
\hline
0.556 & 0.07 & 0.27 & 0.53 & 0.86 & 0.92 & 0.97\\
\hline
0.448 & 0.13 & 0.33 & 0.60 & 0.82 & 0.90 & 0.96\\
\hline
0.37 & 0.20 & 0.47 & 0.73 & 0.77 & 0.85 & 0.92\\
\hline
0.329 & 0.27 & 0.53 & 0.80 & 0.74 & 0.83 & 0.91\\
\hline
0.261 & 0.33 & 0.60 & 0.87 & 0.73 & 0.82 & 0.90\\
\hline
0.243 & 0.40 & 0.67 & 0.87 & 0.72 & 0.81 & 0.88\\
\hline
0.232 & 0.53 & 0.73 & 0.93 & 0.71 & 0.79 & 0.88\\
\hline
0.169 & 0.60 & 0.80 & 1.00 & 0.59 & 0.69 & 0.79\\
\hline
0.127 & 0.67 & 0.87 & 1.00 & 0.53 & 0.63 & 0.73\\
\hline
0.068 & 0.80 & 0.93 & 1.00 & 0.44 & 0.54 & 0.64\\
\hline
0.049 & 1.00 & 1.00 & 1.00 & 0.42 & 0.53 & 0.63\\
\hline
\end{tabular}


\end{knitrout}
\caption{Especificidade e sensibilidade nos máximos locais da curva ROC}
\label{table:roc}
\end{table}

\chapter{Versões dos softwares utilizados}

\begin{itemize}\raggedright
  \item R version 3.2.1 (2015-06-18), \verb|x86_64-pc-linux-gnu|
  \item Locale: \verb|LC_CTYPE=en_US.UTF-8|, \verb|LC_NUMERIC=C|, \verb|LC_TIME=pt_BR.UTF-8|, \verb|LC_COLLATE=en_US.UTF-8|, \verb|LC_MONETARY=pt_BR.UTF-8|, \verb|LC_MESSAGES=en_US.UTF-8|, \verb|LC_PAPER=pt_BR.UTF-8|, \verb|LC_NAME=C|, \verb|LC_ADDRESS=C|, \verb|LC_TELEPHONE=C|, \verb|LC_MEASUREMENT=pt_BR.UTF-8|, \verb|LC_IDENTIFICATION=C|
  \item Base packages: base, datasets, graphics, grDevices,
    methods, parallel, stats, utils
  \item Other packages: caret~6.0-47, data.table~1.9.4,
    doParallel~1.0.8, foreach~1.4.2, ggplot2~1.0.1,
    iterators~1.0.7, knitr~1.9, lattice~0.20-31, plyr~1.8.2,
    pROC~1.8, randomForest~4.6-10
  \item Loaded via a namespace (and not attached):
    BradleyTerry2~1.0-6, brglm~0.5-9, car~2.0-25, chron~2.3-45,
    codetools~0.2-11, colorspace~1.2-4, digest~0.6.8,
    evaluate~0.5.5, formatR~1.2, grid~3.2.1, gtable~0.1.2,
    gtools~3.4.2, highr~0.5, labeling~0.3, lme4~1.1-7,
    MASS~7.3-42, Matrix~1.2-2, mgcv~1.8-6, minqa~1.2.4,
    munsell~0.4.2, nlme~3.1-121, nloptr~1.0.4, nnet~7.3-10,
    pbkrtest~0.4-2, proto~0.3-10, quantreg~5.11, Rcpp~0.11.4,
    reshape2~1.4.1, scales~0.2.4, SparseM~1.6, splines~3.2.1,
    stringr~0.6.2, tools~3.2.1
\end{itemize}


%\input{apendice-b}
%\input{apendice-c}
%\input{apendice-d}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\end{document}
